-- Barber CRM — RLS summary (applied via Supabase migrations)
--
-- Helpers (SECURITY DEFINER; avoid recursion when policies read profiles):
--   public.auth_user_profile()      → current row from profiles (optional utility)
--   public.auth_can_manage_barber(uuid) → true if user owns the barber OR is admin/staff linked to that barber_id
--
-- profiles
--   SELECT: own row OR shop staff/owner for rows with same barber_id
--   INSERT: auth.uid() = id
--   UPDATE: own row OR shop staff/owner for that barber_id
--
-- barbers
--   SELECT: public (find-barber / discovery)
--   INSERT/UPDATE/DELETE: owner_id = auth.uid()
--
-- services / resources
--   SELECT: public for active rows (booking/catalog)
--   ALL: shop manager (owner or admin/staff of barber_id)
--
-- resource_services
--   SELECT: public when linked resource + service are active
--   ALL: shop manager (via resource’s barber_id + service’s barber_id)
--
-- business_settings / business_hours
--   SELECT: public
--   ALL: shop manager
--
-- notification_settings
--   SELECT / ALL: shop manager only
--
-- appointments
--   SELECT: client sees own (client_id = auth.uid()) OR shop manager for barber_id
--   INSERT: client_id = auth.uid() (booking) OR shop manager (FOR ALL)
--   UPDATE: own row OR shop manager
--
-- Note: Service role (server with service key) bypasses RLS for admin scripts/API routes.
